//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedMaterial
    {
        public int Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
